### ISSUE TITLE
ERROR os "ubuntu" version "24.04" not found

### ISSUE THREAD

**Issue by mcarvalhor** [canonical/k8s-operator#107]
### Bug Description

I couldn't deploy Canonical K8s charm on an series other than 24.04 - even when explicitly specifying the Ubuntu series.

If I run:
`juju deploy k8s my-k8s-test-application --channel=latest/edge --revision=59 --series=jammy`
Juju says:
`WARNING series flag is deprecated, use --base instead
ERROR os "ubuntu" version "24.04" not found`

If I run:
`juju deploy k8s my-k8s-test-application --channel=latest/edge --revision=59 --base='ubuntu@24.04'`
Juju says:
`ERROR os "ubuntu" version "24.04" not found`

The current workaround is: using revision 47 - later revisions fail.

### To Reproduce

1. juju deploy k8s my-k8s-test-application --channel=latest/edge --revision=59 --base='ubuntu@22.04'
2. Fails.

### Environment

stg-is-new-canonical-k8s-testing@is-bastion-ps6

Channel: latest/edge
Failing revisions: 48 and above
Working revisions: 47 and below
Juju Controller/Model: 3.1.8
Juju client: 3.1.8-ubuntu-amd64

### Relevant log output

```shell
`juju debug-log` is empty because nothing is even deployed.
```

### Additional context

We have Ubuntu 24.04 available on the cloud.
For instance, `juju add-machine --base="ubuntu@24.04"` works and creates a Noble VM.

**Comment by addyess** [comment]
https://discourse.charmhub.io/t/juju-support-for-the-latest-lts-release-noble-numbat-24-04/14051

i'm not sure how to deploy to noble.  I think this is a issue of juju

```
⚡ juju deploy k8s focal-k8s --channel=1.30/edge --base=ubuntu@20.04
Deployed "focal-k8s" from charm-hub charm "k8s", revision 58 in channel 1.30/beta on ubuntu@20.04/stable

addyess@addyess-dell /home/addyess                                                                                           
⚡ juju deploy k8s jammy-k8s --channel=1.30/edge --base=ubuntu@22.04
Deployed "jammy-k8s" from charm-hub charm "k8s", revision 58 in channel 1.30/beta on ubuntu@22.04/stable

addyess@addyess-dell /home/addyess                                                                                           
⚡ juju deploy k8s noble-k8s --channel=1.30/edge --base=ubuntu@24.04
ERROR os "ubuntu" version "24.04" not found
```

**Comment by mcarvalhor** [comment]
Strangely running `juju deploy k8s focal-k8s --channel=1.30/edge --base=ubuntu@20.04` on my environment (juju v3.1.8) shows this error:
`ERROR storing charm "k8s": retrieving essential metadata for charm "ch:amd64/focal/k8s-58": resolving origin for "ch:amd64/focal/k8s-58": os "ubuntu" version "24.04" not found (not found)`

Even though I am explicitly asking for focal (20.04), it tries to deploy to 24.04 it looks like?

**Comment by addyess** [comment]
@hmlanigan Can you comment on whether or not juju is acting appropriately here

the `k8s` charm is
```yaml
  - build-on:
    - name: ubuntu
      channel: "20.04"
      architectures: [amd64]
    run-on:
    - name: ubuntu
      channel: "20.04"
      architectures: [amd64]
    - name: ubuntu
      channel: "22.04"
      architectures: [amd64]
    - name: ubuntu
      channel: "24.04"
      architectures: [amd64]
```
